// event listener to respond to "Show another quote" button clicks
// when user clicks anywhere on the button, the "printQuote" function is called
document.getElementById('loadQuote').addEventListener("click", printQuote, false);

var quotes;
var quoteOnScreen;

//an array of quotes
quotes = [
  {quote: "When you've robbed a man of everything, he's no longer in your power - he's free again.",
   source: "Aleksandr Solzhenitsyn",
   citation: null,
   year: null,
   tags:"society"},
  {quote: "As I would not be a slave, so I would not be a master. This expresses my idea of democracy.",
   source: "Abraham Lincoln",
   citation: null,
   year: null,
   tags:"society"},
  {quote: "Be yourself; everyone else is already taken.",
   source: "Oscar Wilde",
   citation: null,
   year: null,
   tags:"personality"},
  {quote: "If we could change ourselves, the tendencies in the world would also change.",
   source: "Mahatma Gandhi",
   citation: "The Collected Works of Mahatma Gandhi, Volume XII",
   year: 1913,
   tags:"personality"},
  {quote: "It is far better to be alone, than to be in bad company.",
   source: "George Washington",
   citation: null,
   year: null,
   tags:'society'}
];

/*a function which generates a random number within the range of array's length
and picks an object from the array with index equal to that random number*/
function getRandomQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  return quotes[randomNumber];
}

/*a function which takes random object generated by getRandomQuote function and
displays the values of its properties (qoute, source and other) on the web page*/
function printQuote(quoteOnScreen) {
  var randomQuote = getRandomQuote();
  quoteOnScreen += "<p class='quote'>" + randomQuote.quote +  "</p>";
  quoteOnScreen += "<p class='source'>" + randomQuote.source;
  quoteOnScreen += "<p class='tags'>" + randomQuote.tags;
/* a condition according to which the value of citation property is displayed on the web page*/
  if(randomQuote.citation !== null) {
    quoteOnScreen += "<span class='citation'>" + randomQuote.citation + "</span>";
  }
  /* a condition according to which the value of year property is displayed on the web page*/
  if (randomQuote.year !== null) {
    quoteOnScreen += "<span class='year'>" + randomQuote.year + "</span>";
  }
  quoteOnScreen += "</p>";
  document.getElementById('quote-box').innerHTML = quoteOnScreen;
}

// a function which gets three random numbers and uses them to compose a random color
function getRandomColor() {
var hues = [];

for (var i = 0; i <= 3; i += 1) {
  hues.push(Math.floor(Math.random()*256));
}

var color = 'rgb(' + hues[0] + ',' + hues[1] + ',' + hues[2] + ')';
return color;
}

// a function which sets the background color of the web page to a random color
function changeBackground() {
   document.body.style.background = getRandomColor();
}

// a method which makes a new quote appear on the screen in equal intervals
setInterval(function printQuote(quoteOnScreen) {
  var randomQuote = getRandomQuote();
  quoteOnScreen += "<p class='quote'>" + randomQuote.quote +  "</p>";
  quoteOnScreen += "<p class='source'>" + randomQuote.source;
  quoteOnScreen += "<p class='tags'>" + randomQuote.tags;
/* a condition according to which the value of citation property is displayed on the web page*/
  if(randomQuote.citation !== null) {
    quoteOnScreen += "<span class='citation'>" + randomQuote.citation + "</span>";
  }
  /* a condition according to which the value of year property is displayed on the web page*/
  if (randomQuote.year !== null) {
    quoteOnScreen += "<span class='year'>" + randomQuote.year + "</span>";
  }
  quoteOnScreen += "</p>";
  document.getElementById('quote-box').innerHTML = quoteOnScreen;
}, 10000);
